#!/bin/bash
#Updated:	2015-03-06
#
#License:
#Copyright 2015 Alex Schlegel (schlegel@gmail.com   This work is licensed under
#a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License.  See
#http://creativecommons.org/licenses/by-nc-sa/3.0/ for more information.

PrintUsage()
{
	me=`basename $0`
	
	echo " Description:    backup!"
	echo " "
	echo " Usage:    $me [-o <output>]"
	echo " "
	echo " Options:"
	echo "  -o output: ('default') the output location (default, naga, ilmu)"
	echo "  -r restore rather than backup"
	echo "  -t test (dry run)"
	echo " "
}

#default values
	output='default'
	do_restore=0
	do_test=0

#process options
	while getopts o:rt o; do
		case "$o" in
			o)	output=$OPTARG;;
			r)	do_restore=1;;
			t)	do_test=1;;
			[?])	PrintUsage
					exit 1;;
		esac
	done
	shift $(($OPTIND-1))
	export OPTIND=0

#get the output directory
	case "$output" in
		default)
			output=/home/alex/backup_dst
			;;
		naga)
			output=/media/alex/Naga/backup
			;;
		ilmu)
			output=/media/alex/ilmu/backup
			;;
		*)
			echo "unrecognized output option"
			exit 1
			;;
	esac

t=`date +"%Y%m%d"`

#zenity --question --timeout 5 --text="Start backup?" --display=:0.0

extra_options=''

if [[ $do_test -eq 1 ]] ; then
	extra_options="$extra_options --dry-run"
fi

if [[ $do_restore -eq 1 ]] ; then
	echo 'not implemented'
	exit 1
else
	rsync -arLv --no-l --delete $extra_options --exclude-from '/home/alex/code/shell/alexbackup_exclude.txt' /home/alex/backup_src/ $output | tee "/home/alex/temp/backup_$t.log"
fi
