#!/bin/bash
#Updated:	2013-02-27
#
#License:
#Copyright 2013 Alex Schlegel (schlegel@gmail.com   This work is licensed under
#a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License.  See
#http://creativecommons.org/licenses/by-nc-sa/3.0/ for more information.

PrintUsage()
{
		me=`basename $0`
		
		echo " Description:    display % usage of each CPU core (requires mpstat)"
		echo " "
		echo " Usage:    $me"
	}

mpstat -P ALL 1 1 | grep -E -e "^Average:[ ]+[0-9]" | sed -r "s/^.* ([0-9.]+)/\1/g" | awk '{ print 100-$1}'
