#!/bin/bash
#Updated:	2012-05-03
#
#License:
#Copyright 2012 Alex Schlegel (schlegel@gmail.com   This work is licensed under
#a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License.  See
#http://creativecommons.org/licenses/by-nc-sa/3.0/ for more information.

PrintUsage()
{
	me=`basename $0`
	
	echo " Description:    estimate time to completion, in seconds"
	echo " "
	echo " Usage:    $me start k n"
	echo " "
	echo " Input:"
	echo "  start - start time, in seconds (see now)"
	echo "  k     - the number of tasks completed"
	echo "  n     - the total number of tasks"
}

tStart=$1
k=$2
n=$3

tNow=`date +%s`
tElapsed=$(( tNow - tStart ))

if [ $k -le 0 -o $k -gt $n ]; then
	echo 0
else
	echo $(( tElapsed*(n-k)/k ))
fi
