#!/bin/bash
#Updated:	2009-06-04
#
#License:
#Copyright 2009 Alex Schlegel (schlegel@gmail.com).  This work is licensed under
#a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License.  See
#http://creativecommons.org/licenses/by-nc-sa/3.0/ for more information.

PrintUsage()
{
	echo " Description:	pause with a prompt"
	echo " "
	echo " Usage:	$0 [-t <sleep_time>] <prompt>"
	echo " "
	echo " Options:"
	echo "	t	- continue after <sleep_time> seconds"
	echo "	"
	echo " Input:"
	echo "	<prompt>	- the prompt to display"
}

#default values
	DOSLEEP=0
	tSleep=""

#process options
	while getopts t: o; do
		case "$o" in
			t)		DOSLEEP=1
					tSleep="-t $OPTARG";;
			[?])	PrintUsage
					exit 1;;
		esac
	done
	shift $(($OPTIND-1))
	export OPTIND=0
	
#sleep or pause
	read -s $tSleep -n 1 -p "$*" res
	echo
