#!/bin/bash
#Updated:	2012-11-27
#
#License:
#Copyright 2012 Alex Schlegel (schlegel@gmail.com   This work is licensed under
#a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License.  See
#http://creativecommons.org/licenses/by-nc-sa/3.0/ for more information.

fLock=/tmp/pinmouse.lock

#remove the pin lock file
	if [ -f $fLock ]; then
		rm $fLock
	fi
