#!/bin/bash
#Updated:	2010-04-13
#
#License:
#Copyright 2010 Alex Schlegel (schlegel@gmail.com   This work is licensed under
#a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License.  See
#http://creativecommons.org/licenses/by-nc-sa/3.0/ for more information.

PrintUsage()
{
	me=`basename $0`
	
	echo " Description:    convert a BrainVoyager QX VOI to a NIfTI binary mask"
	echo " "
	echo " Usage:    $me [-r <radius>=1] <base> <input> <output>"
	echo " "
	echo " Options:"
	echo "  <radius>: radius of the sphere to add around each voi coordinate"
	echo " "
	echo " Input:"
	echo "  <base>    - the data file to use as a base"
	echo "  <input>   - the input .voi file"
	echo "  <output>  - the output .nii file"
}

if [ $# -eq 0 ]; then
	PrintUsage
	exit 0;
fi

#default values
	radius=1

#process options
	while getopts r: o; do
		case "$o" in
			r)		radius=$OPTARG;;
			[?])	PrintUsage
					exit 1;;
		esac
	done
	shift $(($OPTIND-1))
	export OPTIND=0

fbase=$1
finput=$2
foutput=$3

#create a blank mask
	roi_blank $fbase $foutput &> /dev/null

#get the VOI coordinates
	IFS=$'\n'
	voi=( $(egrep "[-.0-9]+[[:space:]]+[-.0-9]+[[:space:]]+[-.0-9]+" -o $finput) )
	n=${#voi[*]}
		
#add each sphere
	k=0
	for p in "${voi[@]}"; do
		x=`echo $p | awk '{print $1}'`
		y=`echo $p | awk '{print $2}'`
		z=`echo $p | awk '{print $3}'`
		
		roi_addsphere $foutput $foutput $radius $x $y $z &> /dev/null
		
		k=$(($k+1))
		showstatus "$k of $n points added"
	done
	