#!/bin/bash
#Updated: 2016-08-21
#
#License:
#Copyright 2016 Alex Schlegel (schlegel@gmail.com). This work is licensed under
#a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License. See
#http://creativecommons.org/licenses/by-nc-sa/3.0/ for more information.

print_usage()
{
    echo " Description: initialize a platformio project"
    echo " "
    echo " Usage: init"
    echo " "
}

#init!
    platformio init --board diecimilaatmega328 --board uno --board atmegangatmega168
